name: Deploy Documentation

on:
  push:
    branches: [main]
    paths: ['docs/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          # Using the latest LTS version of Node.js

      - name: Install dependencies
        run: cd docs && npm install
        # Using npm install instead of npm ci since package-lock.json might not exist

      - name: Build website
        run: cd docs && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com